// Time constants (calculations)
const DAYS_PER_WEEK = 7;
const HOURS_PER_DAY = 24;
const MINUTES_PER_HOUR = 60;
const SECONDS_PER_MINUTE = 60;
const MILLISECONDS_PER_SECOND = 1000;

// Token expiry durations (in minutes/hours - these are business logic)
const RESET_TOKEN_EXPIRES_IN = 10; // minutes
const EMAIL_VERIFICATION_TOKEN_EXPIRES_IN = 10; // minutes
const USER_TOKEN_EXPIRES_IN = 24; // hours
const OAUTH_EXCHANGE_EXPIRY = 10; // minutes

// Convert to milliseconds for actual usage

const OAUTH_EXCHANGE_EXPIRY_MS =
  OAUTH_EXCHANGE_EXPIRY * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;

const RESET_TOKEN_EXPIRY_MS =
  RESET_TOKEN_EXPIRES_IN *
  MINUTES_PER_HOUR *
  SECONDS_PER_MINUTE *
  MILLISECONDS_PER_SECOND;
const EMAIL_VERIFICATION_TOKEN_EXPIRY_MS =
  EMAIL_VERIFICATION_TOKEN_EXPIRES_IN *
  MINUTES_PER_HOUR *
  SECONDS_PER_MINUTE *
  MILLISECONDS_PER_SECOND;
const USER_TOKEN_EXPIRY_MS =
  USER_TOKEN_EXPIRES_IN *
  HOURS_PER_DAY *
  MINUTES_PER_HOUR *
  SECONDS_PER_MINUTE *
  MILLISECONDS_PER_SECOND;

// Application constants
const DEFAULT_PAGE_SIZE = 20;
const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
const ALLOWED_FILE_TYPES = ["image/jpeg", "image/png", "image/gif"];

module.exports = {
  DAYS_PER_WEEK,
  HOURS_PER_DAY,
  MINUTES_PER_HOUR,
  SECONDS_PER_MINUTE,
  MILLISECONDS_PER_SECOND,
  RESET_TOKEN_EXPIRES_IN,
  EMAIL_VERIFICATION_TOKEN_EXPIRES_IN,
  USER_TOKEN_EXPIRES_IN,
  OAUTH_EXCHANGE_EXPIRY,
  OAUTH_EXCHANGE_EXPIRY_MS,
  RESET_TOKEN_EXPIRY_MS,
  EMAIL_VERIFICATION_TOKEN_EXPIRY_MS,
  USER_TOKEN_EXPIRY_MS,
  DEFAULT_PAGE_SIZE,
  MAX_FILE_SIZE,
  ALLOWED_FILE_TYPES,
};
